controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - coxa_1_joint
        - femur_1_joint
        - tibia_1_joint
        - coxa_2_joint
        - femur_2_joint
        - tibia_2_joint
        - coxa_3_joint
        - femur_3_joint
        - tibia_3_joint
        - coxa_4_joint
        - femur_4_joint
        - tibia_4_joint
        - coxa_5_joint
        - femur_5_joint
        - tibia_5_joint
        - coxa_6_joint
        - femur_6_joint
        - tibia_6_joint

      command_interfaces:
        - position

      state_interfaces:
        - position
        - velocity

